### ISSUE TITLE
fix(server): broken shutdown_tx in run_server after #1704 merged onto post-#1945 main

### ISSUE THREAD

**Issue by st-gr** [NVIDIA/OpenShell#2026]
## Symptom

`cargo build` / `cargo check -p openshell-server` fails on current `main` (commit `4ee27d99`) with:

\`\`\`
error[E0425]: cannot find value `shutdown_tx` in this scope
   --> crates/openshell-server/src/lib.rs:460:13
    |
460 |     let _ = shutdown_tx.send(true);
    |             ^^^^^^^^^^^ help: a local variable with a similar name exists: `_shutdown_tx`
\`\`\`

`rust-toolchain.toml` pins `1.95.0`; reproduces under any clean checkout of `main`.

## Cause

`crates/openshell-server/src/lib.rs::run_server` declares `(_shutdown_tx, shutdown_rx)` at line 347 (with the unused-prefix `_`) but uses `shutdown_tx.send(true)` at line 460. The names don't match — won't compile.

Land-order regression between two individually-correct PRs:

- **#1945 `fix(server): share gateway shutdown channel`** (merged 2026-06-17, commit `4c75b854`) made the first `shutdown_tx` in `run_server` used by adding the `shutdown_tx.send(true)` call at the new shutdown-signal block. That's correct against the pre-#1945 main where the variable was unused.
- **#1704 `feat(sandbox,providers): add aws-bedrock as a recognized inference provider`** (merged 2026-06-23, commit `4ee27d99`) included a drive-by `style(server): silence unused-variable lint on first shutdown_tx` commit that prefixed the declaration with `_`. That was correct against the main #1704 branched from (pre-#1945) where the variable was genuinely unused, but became wrong after #1945 made it used.

Neither PR's CI re-validated the combined post-merge state, so the regression landed on `main` without surfacing.

This is exactly the integration gap @elezar described in #1946.

## Fix

One line in `crates/openshell-server/src/lib.rs`:

\`\`\`diff
-    let (_shutdown_tx, shutdown_rx) = watch::channel(false);
+    let (shutdown_tx, shutdown_rx) = watch::channel(false);
\`\`\`

I verified this locally — applying the rename clears the build error, the rest of the workspace builds clean, and the existing `cargo test -p openshell-server --lib` suite passes (833/833).

## Related

- Introduced by #1704 (interaction with #1945's earlier change).
- Long-term prevention is what #1946 proposes (merge queue for `main`).

Happy to open a one-line PR if it speeds things up.

**Comment by st-gr** [comment]
Fixed upstream in [PR #1985 `fix(ci): fix linting issues`](https://github.com/NVIDIA/OpenShell/pull/1985) (commit `8e831f3a`). Verified `main` at `0a25fdf5` now compiles cleanly — line 366 reads `let (shutdown_tx, shutdown_rx) = watch::channel(false);` (no underscore).

Confirmed downstream by pulling the released `0.0.73` gateway image (`sha256:523609f8...`) and running it against my Kyma cluster. Safe to close.
