### PR TITLE
fix(driver-mxc): implement authenticate_sandbox trait method

### LINKED ISSUE #3155: bug: mxc crate build is broken
## User Story

As a developer working on OpenShell, I want the `openshell-driver-mxc` crate to compile successfully, so that I can build and test the full project on Windows.

## Problem Statement

The `openshell-driver-mxc` crate fails to compile after commit 9b6d904e ("delegate sandbox authentication to drivers") introduced the `authenticate_sandbox` method on the `ComputeDriver` trait and added a `supports_sandbox_authentication` field to `GetCapabilitiesResponse`. The mxc driver was not updated to implement the new trait method or include the new field.

## Impact / Why This Matters

Any developer attempting to build the full workspace or specifically the mxc crate hits a compile error, blocking all mxc-related development and testing on Windows. There is no workaround short of manually patching the code locally.

## Acceptance Criteria

- [ ] `cargo check -p openshell-driver-mxc` compiles without errors
- [ ] `ComputeDriverService` implements the `authenticate_sandbox` trait method
- [ ] `GetCapabilitiesResponse` initializer includes the `supports_sandbox_authentication` field

## Reproduction Steps

1. Check out the `main` branch at or after commit `9b6d904e`
2. Run `cargo check -p openshell-driver-mxc`
3. Observe two compilation errors:
   - `E0046`: missing `authenticate_sandbox` in `ComputeDriver` impl (`grpc.rs:36`)
   - `E0063`: missing field `supports_sandbox_authentication` in `GetCapabilitiesResponse` (`driver.rs:302`)

## Environment

- OpenShell: main branch @ `9b6d904e`
- OS: Windows 11 Enterprise 10.0.26200
- Rust: 1.95.0 (59807616e 2026-04-14)

## Logs

```
error[E0046]: not all trait items implemented, missing: `authenticate_sandbox`
  --> crates\openshell-driver-mxc\src\grpc.rs:36:1
   |
36 | impl ComputeDriver for ComputeDriverService {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `authenticate_sandbox` in implementation

error[E0063]: missing field `supports_sandbox_authentication` in initializer of `GetCapabilitiesResponse`
   --> crates\openshell-driver-mxc\src\driver.rs:302:9
    |
302 |         GetCapabilitiesResponse {
    |         ^^^^^^^^^^^^^^^^^^^^^^^ missing `supports_sandbox_authentication`
```

### PR DESCRIPTION
**Pull request by jeffmaury**
> **🏗️ build-from-issue-agent**

## Summary
Add the missing `authenticate_sandbox` method to the MXC driver's `ComputeDriver` impl, fixing the compilation error introduced by commit 9b6d904e. The method returns `Status::unimplemented`, matching the Docker and Podman drivers, since the MXC driver advertises `supports_sandbox_authentication: false`.

## Related Issue
Closes #3155

## Changes
- `crates/openshell-driver-mxc/src/grpc.rs`: Added `AuthenticateSandboxRequest`/`AuthenticateSandboxResponse` imports and implemented `authenticate_sandbox` returning `Status::unimplemented("mxc does not authenticate sandbox credentials")`

### Deviations from Plan
None — implemented as planned. The `supports_sandbox_authentication` field in `driver.rs` was already present (set to `false`), so only the trait method in `grpc.rs` needed adding.

## Testing
- [x] `mise run pre-commit` passes (proto:lint failure is pre-existing Windows env issue)
- [x] `cargo check -p openshell-driver-mxc` compiles cleanly
- [x] `cargo test -p openshell-driver-mxc` — all 75 tests pass (27 unit + 48 integration, 9 ignored as expected)

**Tests added:**
- **Unit:** N/A — one-line unimplemented stub behind a capability gate; matches Docker/Podman pattern which also don't test their stubs
- **Integration:** N/A
- **E2E:** N/A

## Checklist
- [x] Follows Conventional Commits
- [x] Commits are signed off (DCO)

**Documentation updated:**
- None needed — mechanical trait conformance fix with no user-facing behavior change

### CODE REVIEW

**Review by johntmyers — APPROVED** [review]

**Comment by johntmyers** [comment]
/ok to test [59d9d57](https://github.com/NVIDIA/OpenShell/pull/3158/commits/59d9d575f17278ecebb7e3e31ec1f76720b5ba08)
